Repository Clean-Software/purrfect-components, pull requests merged in 2022-01, with the labels that each got.

#2 Config of webpack
  .babelrc
  .eslintrc.json
  .prettierrc.json
  package.json
  src/App.tsx
  src/index.tsx
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: enhancement

#4 setup ci for react
  .github/workflows/node.js.yml
Labels: enhancement

#5 Test/button component
  src/App.css
  src/App.tsx
  src/button/index.tsx
  src/index.css
  src/index.ts
  src/index.tsx
  tsconfig.json
  webpack.config.ts
Labels: enhancement

#7 base config of StoryBooks
  .eslintrc.json
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/button/button.css
  src/button/index.tsx
  src/index.ts
  src/stories/Button.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/header.css
  src/stories/page.css
  tsconfig.json
  yarn.lock
Labels: enhancement

#8 Feat/input component
  .babelrc
  package.json
  src/button/index.tsx
  src/button/styles.scss
  src/index.ts
  src/input/index.tsx
  src/input/styles.scss
  src/stories/Header.tsx
  src/stories/Input.stories.tsx
  src/stories/Page.tsx
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: enhancement

#16 Rollup Configuration
  package.json
  rollup.config.ts
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: bug, enhancement

#14 ✨ feat : create initial checkbox component
  src/components/checkbox/index.tsx
  src/components/checkbox/styles.ts
  src/index.ts
  src/stories/Checkbox.stories.tsx
Labels: enhancement

#19 ✨ feat : adding license MIT
  LICENSE
  package.json
Labels: documentation

#20 ⚡️ fix : ignore stories types in dist dir
  rollup.config.ts
  src/stories/Header.stories.tsx
  src/stories/Header.test.tsx
  src/stories/Page.stories.tsx
  src/stories/Page.test.tsx
  tsconfig.json
Labels: bug

#24 ✨ feat:: improving rollup
  package.json
  rollup.config.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#26 🔥 Feat/button group component
  package.json
  src/components/button/index.tsx
  src/components/buttonGroup/index.tsx
  src/components/buttonGroup/styles.ts
  src/index.ts
  src/stories/Button.stories.tsx
  src/stories/buttonGroup.stories.tsx
  yarn.lock
Labels: enhancement

#27 Refactor/checkbox cursor
  .eslintrc.json
  package-lock.json
  package.json
  src/components/checkbox/index.tsx
  src/components/checkbox/styles.ts
  yarn.lock
Labels: bug

#28 Refactor/clean code
  .eslintrc.json
  README.md
  rollup.config.ts
  src/components/button/index.tsx
  src/components/input/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.test.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.test.tsx
  src/stories/buttonGroup.stories.tsx
  src/stories/header.scss
  src/stories/page.scss
  yarn.lock
Labels: bug

#29 ✨ feat : add label component
  package.json
  src/components/button/index.tsx
  src/components/label/index.tsx
  src/components/label/styles.ts
  src/index.ts
  src/stories/Label.stories.tsx
  yarn.lock
Labels: enhancement

#32 version 0.0.0
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/titulo.md
  .github/workflows/node.js.yml
  .gitignore
  .prettierrc.json
  .storybook/main.js
  .storybook/preview.js
  LICENSE
  README.md
  README.old.md
  package-lock.json
  package.json
  rollup.config.ts
  src/App.css
  src/App.tsx
  src/components/button/index.tsx
  src/components/button/styles.ts
  src/components/buttonGroup/index.tsx
  src/components/buttonGroup/styles.ts
  src/components/checkbox/index.tsx
  src/components/checkbox/styles.ts
  src/components/input/index.tsx
  src/components/input/styles.ts
  src/components/label/index.tsx
  src/components/label/styles.ts
  src/index.css
  src/index.ts
  src/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Checkbox.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/Label.stories.tsx
  src/stories/buttonGroup.stories.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#33 ✨ feat: publish storybook in github page
  .gitignore
  package.json
  yarn.lock
Labels: enhancement
